apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 30
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
#        imagePullPolicy: Always
#        image: registry.blogdobill.com:5000/nginx_of_bill:latest
        image: nginx
        ports:
        - containerPort: 80
